Repository gyeonggido-idle/issue-tracker-max, pull requests merged in 2023-08, with the labels that each got.

#17 [BE]: 메인페이지 기능 구현 중(2) (#15)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/Issue.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/FilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/IssueResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/IssueInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/Label.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/response/LabelResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/Member.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/Milestone.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/ControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/ServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueServiceTest.java
Labels: BE, feat, test

#18 [BE]: sql, test코드 수정 (#15)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepositoryTest.java
Labels: BE, feat

#21 [BE]: 메인 페이지 기능 완성 (#15)
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/IntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
Labels: BE, test

#22 [FE]: button 컴포넌트 구현 (#6)
  fe/.prettierrc.json
  fe/src/App.tsx
  fe/src/ComponentTest.tsx
  fe/src/components/Button/Button.tsx
  fe/src/components/Icon/Icon.tsx
  fe/src/components/Icon/SvgIcons.tsx
Labels: FE, feat, design

#24 [FE]: 드롭다운 인디케이터 및 패널 구현 (#19) (#20)
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/components/Dropdown/Dropdown.tsx
  fe/src/components/Dropdown/DropdownIndicator.tsx
  fe/src/components/Dropdown/DropdownOptions.tsx
  fe/src/components/Dropdown/DropdownTap.tsx
  fe/src/components/Dropdown/DropdownTitle.tsx
  fe/src/components/Header/IssueListHeader.tsx
  fe/src/main.tsx
  fe/src/mocks/data/subFilters.ts
  fe/src/mocks/handler.ts
  fe/src/mocks/worker.ts
  fe/src/pages/Layout.tsx
  fe/src/pages/Main.tsx
  fe/src/styles/GlobalStyles.tsx
Labels: FE, feat, design

#27 [FE]: Infomation Tag 컴포넌트 구현 (#26)
  fe/src/App.tsx
  fe/src/ComponentTest.tsx
  fe/src/components/Button/Button.tsx
  fe/src/components/Dropdown/DropdownIndicator.tsx
  fe/src/components/Header.tsx
  fe/src/components/Icon/Icon.tsx
  fe/src/components/Icon/SvgIcons.tsx
  fe/src/components/Tag/Tag.tsx
  fe/src/constants/icons.tsx
  fe/src/contexts/ThemeModeContext.tsx
  fe/src/main.tsx
  fe/src/pages/Layout.tsx
  fe/src/routes/router.tsx
  fe/src/styles/Theme.tsx
Labels: FE, feat, design

#30 [BE]: 레이블 관리페이지, 마일스톤 관리페이지 구현 (#25)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/LabelController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/response/LabelDetailsResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/response/LabelPageResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/VO/LabelDetailsVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/LabelService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/information/LabelDetailsInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/information/LabelPageInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/response/MilestoneDetailsResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/response/MilestonePageResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/vo/MilestoneDetailsVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/information/MilestoneDetailsInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/information/MilestonePageInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/vo/IssueByMilestoneVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/vo/MilestoneStatVO.java
  be/src/main/resources/data.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/LabelControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/integration/LabelIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/LabelServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepositoryTest.java
  be/src/test/resources/schema/data.sql
Labels: BE, feat, test

#32 [FE]: input 컴포넌트 구현 (#28)
  fe/src/ComponentTest.tsx
  fe/src/components/Input/Input.tsx
Labels: FE, feat, design

#37 [FE]: Tab Button 컴포넌트 구현
  fe/src/ComponentTest.tsx
  fe/src/assets/icons/label.svg
  fe/src/assets/icons/milestone.svg
  fe/src/components/Button/Button.tsx
  fe/src/components/Button/TabButton.tsx
Labels: FE, feat, design

#40 [FE]: FilterBar 컴포넌트 구현 (#34)
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/App.tsx
  fe/src/ComponentTest.tsx
  fe/src/components/Dropdown/DropdownOptions.tsx
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/Header/IssueListHeader.tsx
  fe/src/components/Input/Input.tsx
  fe/src/main.tsx
  fe/src/mocks/data/subFilters.ts
  fe/src/mocks/handler.ts
  fe/src/mocks/worker.ts
  fe/vite.config.ts
Labels: FE, feat, design

#44 [FE]: 메인 페이지 UI 구현 (#41)
  fe/src/App.tsx
  fe/src/assets/img/profile_test.svg
  fe/src/components/Button/TabButton.tsx
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/Header.tsx
  fe/src/components/Header/IssueListHeader.tsx
  fe/src/components/Header/IssueTableHeader.tsx
  fe/src/components/Header/MainHeader.tsx
  fe/src/components/Table/IssuesTable.tsx
  fe/src/components/Tag/Tag.tsx
  fe/src/pages/Issues.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/Main.tsx
  fe/src/routes/router.tsx
  fe/vite.config.ts
Labels: FE, feat, design

#46 [FE] 전체적인 이름 수정 및 디렉토리 수정 (#45)
  fe/src/ComponentTest.tsx
  fe/src/components/Button/Button.tsx
  fe/src/components/Common/Button/Button.tsx
  fe/src/components/Common/Button/TabButton.tsx
  fe/src/components/Common/FilterBar/FilterBar.tsx
  fe/src/components/Common/Icon/Icon.tsx
  fe/src/components/Common/Icon/SvgIcons.tsx
  fe/src/components/Common/Input/Input.tsx
  fe/src/components/Common/Tag/Tag.tsx
  fe/src/components/Dropdown/DropdownIndicator.tsx
  fe/src/components/Dropdown/DropdownOptions.tsx
  fe/src/components/Header/IssueListHeader.tsx
  fe/src/components/Header/MainHeader.tsx
  fe/src/components/Table/IssueTableHeader.tsx
  fe/src/components/Table/IssueTableItem.tsx
  fe/src/components/Table/IssueTableList.tsx
  fe/src/components/Table/IssuesTable.tsx
  fe/src/pages/Issues.tsx
  fe/src/pages/Layout.tsx
Labels: refactor

#36 [BE]: 메인화면 필터 내려주기 기능 구현 (#35)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/AssigneeFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/AuthorFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/FilterListResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/LabelFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/MilestoneFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/AssigneeFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/AuthorFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/FilterListInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/LabelFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/MilestoneFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/vo/MemberDetailsVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/member/repository/MemberRepositoryTest.java
Labels: BE, feat

#47 [BE]: be-feature/sendFilters 브랜치 dev-be로 병합
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/AssigneeFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/AuthorFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/FilterListResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/LabelFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/MilestoneFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/AssigneeFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/AuthorFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/FilterListInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/LabelFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/MilestoneFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/vo/MemberDetailsVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/member/repository/MemberRepositoryTest.java
Labels: BE

#48 [FE]: Input, FilterBar 컴포넌트 리팩토링 (#45)
  fe/src/ComponentTest.tsx
  fe/src/components/Common/FilterBar/FilterBar.tsx
  fe/src/components/Common/Input/TextInput.tsx
Labels: refactor

#50 [FE]: ProgressBar 컴포넌트 구현 (#49)
  fe/src/ComponentTest.tsx
  fe/src/components/Common/Bar/ProgressBar.tsx
Labels: FE, feat, design

#54 [BE]: 2주차 pr리뷰 반영
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepository.java
Labels: BE, refactor, review

#55 [BE]: 리뷰 적용하여 리팩토링 (#53)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/AssigneeFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/AuthorFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/FilterListResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/LabelFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/MilestoneFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/AssigneeFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/AuthorFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/FilterListInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/LabelFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/MilestoneFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/response/LabelDetailsResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/response/LabelPageResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/LabelService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/information/LabelDetailsInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/information/LabelPageInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/response/MilestoneDetailsResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/response/MilestonePageResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/vo/MilestoneDetailsVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/information/MilestoneDetailsInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/information/MilestonePageInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepository.java
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/RepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/ServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/LabelControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/integration/LabelIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/LabelServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/member/repository/MemberRepositoryTest.java
  be/src/test/resources/schema/data.sql
Labels: BE, refactor, chore

#56 [BE]: 리뷰 적용하여 리팩토링 (#53)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/AssigneeFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/AuthorFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/FilterListResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/LabelFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/MilestoneFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/AssigneeFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/AuthorFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/FilterListInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/LabelFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/MilestoneFilterInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/response/LabelDetailsResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/response/LabelPageResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/LabelService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/information/LabelDetailsInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/information/LabelPageInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/response/MilestoneDetailsResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/response/MilestonePageResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/vo/MilestoneDetailsVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/information/MilestoneDetailsInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/information/MilestonePageInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepository.java
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/RepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/annotation/ServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/LabelControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/integration/LabelIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/LabelServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/member/repository/MemberRepositoryTest.java
  be/src/test/resources/schema/data.sql
Labels: BE, refactor

#52 [BE]: 이슈 작성, 수정, 삭제 기능 구현(#42)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/repository/CommentRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/Comment.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/request/IssueStatusRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/request/IssueUpdateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/ApiResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/vo/IssueStatusVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/vo/IssueUpdateVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueStatusCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueUpdateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
Labels: BE, feat

#60 [FE]: Issue 페이지 수정 & Textarea, comment 컴포넌트 구현
  fe/src/components/Common/Comment/Comment.tsx
  fe/src/components/Common/Sidebar/Sidebar.tsx
  fe/src/components/Common/Tag/Tag.tsx
  fe/src/components/Common/TextArea/TextArea.tsx
  fe/src/components/Header/IssueListHeader.tsx
  fe/src/components/Table/IssueTableHeader.tsx
  fe/src/components/Table/IssueTableItem.tsx
  fe/src/components/Table/IssueTableList.tsx
  fe/src/pages/Issues.tsx
  fe/src/styles/Theme.tsx
  fe/vite.config.ts
Labels: FE, feat, design

#66 [FE]: 전체 페이지 UI 구현 (#61)
  fe/src/App.tsx
  fe/src/ComponentTest.tsx
  fe/src/components/Common/Bar/ProgressBar.tsx
  fe/src/components/Common/Button/TabButton.tsx
  fe/src/components/Common/Comment/Comment.tsx
  fe/src/components/Common/Input/TextInput.tsx
  fe/src/components/Common/TextArea/TextArea.tsx
  fe/src/components/Header/IssueListHeader.tsx
  fe/src/components/Header/MainHeader.tsx
  fe/src/components/Table/IssueTableHeader.tsx
  fe/src/pages/Error.tsx
  fe/src/pages/IssueDetail.tsx
  fe/src/pages/Issues.tsx
  fe/src/pages/Labels.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/Loading.tsx
  fe/src/pages/Login.tsx
  fe/src/pages/Milestones.tsx
  fe/src/pages/NewIssue.tsx
  fe/src/routes/router.tsx
  fe/src/styles/GlobalStyles.tsx
Labels: FE, feat, design

#68 [BE] 필터 기능 구현 (#59)
  be/build.gradle
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/Filter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueStatusRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueUpdateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/ApiResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/AssigneeFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/AuthorFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/FilterListResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/FilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/IssueResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/LabelFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/MilestoneFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/FilteredIssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/main/resources/mapper/filter.xml
  be/src/main/resources/mapper/testSchema.xml
  be/src/main/resources/mybatis/MybatisConfig.xml
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/FilterTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/FilteredIssueRepositoryTest.java
Labels: BE, feat

#62 [BE]: JWT 로그인, 로그아웃 기능 구현 (#57)
  be/build.gradle
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/FilterConfig.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/ApiResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/JwtAuthorizationFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/JwtController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/LoginRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/RefreshTokenRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/SignUpRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtTokenType.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/entity/Jwt.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/entity/JwtProvider.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/repository/JwtRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/JwtService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/condition/LoginCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/condition/SignUpCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/Member.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/CustomException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/GlobalExceptionHandler.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/IllegalEmailException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/IllegalJwtTokenException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/IllegalPasswordException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/JwtExceptionType.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/MemberDuplicationException.java
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/integration/JwtIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/integration/LabelIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/member/repository/MemberRepositoryTest.java
  be/src/test/resources/schema/schema.sql
Labels: BE, feat

#69 [BE]: JWT 로그인, 로그아웃 기능 구현 (#57) (#62)
  be/build.gradle
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/FilterConfig.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/contoller/response/ApiResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/JwtAuthorizationFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/JwtController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/LoginRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/RefreshTokenRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/SignUpRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtTokenType.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/entity/Jwt.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/entity/JwtProvider.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/repository/JwtRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/JwtService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/condition/LoginCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/condition/SignUpCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/Member.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/CustomException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/GlobalExceptionHandler.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/IllegalEmailException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/IllegalJwtTokenException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/IllegalPasswordException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/JwtExceptionType.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/MemberDuplicationException.java
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/integration/JwtIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/integration/LabelIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/member/repository/MemberRepositoryTest.java
  be/src/test/resources/schema/schema.sql
Labels: BE, feat

#73 [BE]: 마일스톤 CRUD 기능 구현 (#65)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/request/MilestoneRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/MilestoneService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/condition/MilestoneCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/condition/MilestoneUpdateCondition.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
Labels: BE, feat

#75 [FE]: 메인 페이지 필터 및 드롭박스 관련 수정 (#67)
  fe/src/ComponentTest.tsx
  fe/src/components/Common/FilterBar/FilterBar.tsx
  fe/src/components/Common/Profile/Profile.tsx
  fe/src/components/Dropdown/DropdownIndicator.tsx
  fe/src/components/Dropdown/DropdownOptions.tsx
  fe/src/components/Dropdown/DropdownPanel.tsx
  fe/src/components/Dropdown/DropdownTap.tsx
  fe/src/components/Dropdown/DropdownTitle.tsx
  fe/src/components/Header/IssueHeader.tsx
  fe/src/components/Header/MainHeader.tsx
  fe/src/components/Table/IssueTable.tsx
  fe/src/components/Table/IssueTableHeader.tsx
  fe/src/components/Table/IssueTableItem.tsx
  fe/src/pages/Issues.tsx
  fe/src/pages/Milestones.tsx
  fe/vite.config.ts
Labels: FE, feat, refactor

#77 [BE]: be-feature/filter 브랜치 dev-be로 머지
  be/build.gradle
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/Filter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueStatusRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueUpdateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/ApiResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/AssigneeFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/AuthorFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/FilterListResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/FilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/IssueResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/LabelFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/MilestoneFilterResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/FilteredIssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/JwtAuthorizationFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/JwtController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/LabelController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/GlobalExceptionHandler.java
  be/src/main/resources/application.yml
  be/src/main/resources/data.sql
  be/src/main/resources/mapper/filter.xml
  be/src/main/resources/mapper/testSchema.xml
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/FilterTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/FilteredIssueRepositoryTest.java
Labels: BE, feat

#80 [FE]: 메인 페이지 필터 기능 구현 (#67)
  fe/src/components/Common/Bar/ProgressBar.tsx
  fe/src/components/Common/TextArea/TextArea.tsx
  fe/src/components/Dropdown/DropdownOptions.tsx
  fe/src/components/Dropdown/DropdownPanel.tsx
  fe/src/components/Dropdown/DropdownTap.tsx
  fe/src/components/Header/IssueHeader.tsx
  fe/src/components/Table/IssueTable.tsx
  fe/src/contexts/FilterProvider.tsx
  fe/src/pages/Issues.tsx
  fe/src/routes/router.tsx
Labels: FE, feat

#83 [BE]: 3주차 리뷰 반영 (#81)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/Comment.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/Issue.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueStatusRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueUpdateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/ApiResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueUpdateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/JwtAuthorizationFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/AuthenticationController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/LoginRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/RefreshTokenRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/repository/JwtRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/JwtService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/Label.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/request/LabelRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/condition/LabelCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/condition/LabelUpdateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/controller/MemberController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/controller/request/SignUpRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/service/MemberService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/Milestone.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/request/MilestoneRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/request/MilestoneStatusRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/vo/MilestoneDetailsVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/GlobalExceptionHandler.java
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/integration/JwtIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/integration/LabelIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/member/integration/MemberIntegrationTest.java
Labels: BE, refactor, review

#84 [BE]: 3주차 리뷰 반영 (#81) (#83)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/Comment.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/Issue.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueStatusRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueUpdateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/ApiResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueUpdateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/JwtAuthorizationFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/AuthenticationController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/LoginRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/request/RefreshTokenRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/repository/JwtRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/JwtService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/Label.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/request/LabelRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/condition/LabelCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/service/condition/LabelUpdateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/controller/MemberController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/controller/request/SignUpRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/service/MemberService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/Milestone.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/request/MilestoneRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/request/MilestoneStatusRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/vo/MilestoneDetailsVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/GlobalExceptionHandler.java
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/integration/JwtIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/integration/LabelIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/repository/LabelRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/member/integration/MemberIntegrationTest.java
Labels: BE, review

#86 [BE]: jwt 리팩토링
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/GlobalExceptionHandler.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/AuthenticationController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtLoginResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/JwtService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/information/JwtLoginInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/GlobalExceptionHandler.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/integration/JwtIntegrationTest.java
Labels: BE, feat, refactor

#87 [BE]: jwt 리팩토링 (#86)
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/GlobalExceptionHandler.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/AuthenticationController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtLoginResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/JwtService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/information/JwtLoginInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/GlobalExceptionHandler.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/integration/JwtIntegrationTest.java
Labels: BE

#88 [BE]: jwt 테스트 코드 수정
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/integration/JwtIntegrationTest.java
Labels: BE, test

#94 [BE]: github로 로그인 기능 구현 (#93)
  .gitignore
  be/build.gradle
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/FilterConfig.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/GlobalExceptionHandler.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/OauthConfig.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/filter/CorsFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/filter/JwtAuthorizationFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/OauthAdapter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/OauthAttributes.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/OauthProperties.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/AuthenticationController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/request/LoginRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/request/RefreshTokenRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/response/JwtLoginResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/response/JwtResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/response/JwtTokenType.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/response/OauthTokenResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/entity/Jwt.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/entity/JwtProvider.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/entity/OauthProvider.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/entity/UserProfile.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/repository/InMemoryProviderRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/repository/JwtTokenRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/JwtService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/OauthService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/condition/LoginCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/condition/SignUpCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/information/JwtLoginInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/repository/CommentRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueStatusPatchRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueUpdateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/AuthenticationController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtTokenType.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/information/JwtLoginInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/LabelController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/request/LabelRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/controller/request/SignUpRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/service/MemberService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/request/MilestoneRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/request/MilestoneStatusRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/IllegalJwtTokenException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/MemberNotFoundException.java
  be/src/main/resources/application.yml
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/integration/JwtIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/integration/LabelIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
Labels: BE, feat

#97 [BE]: github로 로그인 기능 구현 (#93) (#94)
  .gitignore
  be/build.gradle
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/FilterConfig.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/GlobalExceptionHandler.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/OauthConfig.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/filter/CorsFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/filter/JwtAuthorizationFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/OauthAdapter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/OauthAttributes.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/OauthProperties.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/AuthenticationController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/request/LoginRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/request/RefreshTokenRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/response/JwtLoginResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/response/JwtResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/response/JwtTokenType.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/controller/response/OauthTokenResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/entity/Jwt.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/entity/JwtProvider.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/entity/OauthProvider.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/entity/UserProfile.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/repository/InMemoryProviderRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/repository/JwtTokenRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/JwtService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/OauthService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/condition/LoginCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/condition/SignUpCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/auth/service/information/JwtLoginInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/repository/CommentRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueStatusPatchRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueUpdateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/AuthenticationController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/controller/response/JwtTokenType.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/service/information/JwtLoginInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/LabelController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/controller/request/LabelRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/controller/request/SignUpRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/repository/MemberRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/member/service/MemberService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/MilestoneController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/request/MilestoneRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/request/MilestoneStatusRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/IllegalJwtTokenException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/MemberNotFoundException.java
  be/src/main/resources/application.yml
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/integration/IssueIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/jwt/integration/JwtIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/label/integration/LabelIntegrationTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/integration/MilestoneIntegrationTest.java
Labels: BE, feat

#100 [BE]: 코멘트 CRUD작성, 이슈 상세 페이지 작성
  be/build.gradle
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/config/filter/JwtAuthorizationFilter.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/Comment.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/controller/CommentController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/controller/request/CommentCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/controller/request/CommentUpdateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/controller/response/CommentResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/repository/CommentRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/repository/result/CommentResult.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/service/CommentService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/service/condition/CommentCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/service/condition/CommentUpdateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/service/information/CommentInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/file/controller/FileController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/file/service/FileService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueController.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/request/IssueCreateRequest.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/IssueDetailResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/response/IssueResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/result/IssueDetailResult.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueService.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/condition/IssueCreateCondition.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/information/IssueDetailInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/controller/response/MilestoneResponse.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/vo/MilestoneVO.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/service/information/MilestoneInformation.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepository.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/EmptyFileException.java
  be/src/main/java/codesquad/kr/gyeonggidoidle/issuetracker/exception/FileUploadFailedException.java
  be/src/main/resources/data.sql
  be/src/main/resources/schema.sql
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/comment/repository/CommentRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/controller/IssueControllerTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/repository/IssueRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/issue/service/IssueServiceTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/milestone/repository/MilestoneRepositoryTest.java
  be/src/test/java/codesquad/kr/gyeonggidoidle/issuetracker/domain/stat/repository/StatRepositoryTest.java
  be/src/test/resources/schema/schema.sql
Labels: BE, feat
